### ISSUE TITLE
All slider ui elements stop working after some time

### ISSUE THREAD

**Issue by kennymc-c** [albaintor/UC-Remote#18]
All ui slider elements e.g. for brightness or covers only seem to work for a limited time. I can change the brightness 2 or 3 times and then I'm not able to move the slider anymore for any entity that uses sliders. Even killing and restarting the app doesn't help to fix it. I think the update to the lasted build had reactivated the function so maybe there is something permanent stored that gets reset/deleted with an update.

**Comment by kennymc-c** [comment]
I think this could also be related to touch controls as it works better when running the app on my Mac although I sometimes still see this issue there too but not constantly.

**Comment by albaintor** [comment]
This should be better now with build 111. Please confirm.

Of course playing with sliders may not always work : the connection chain may fail or with a response time that may not be fast enough.
I have random lags with my chain remote -> home assistant -> target device (ex philips hue)

**Comment by kennymc-c** [comment]
I can't notice a difference with Build 111. Using sliders just results in moving the pop up window up and down. The color wheel and the switch are working like excepted. I'm using the Hue integration for lights.

**Comment by albaintor** [comment]
Not sure to understand your problem :
- moving slider results in moving pages ?
- sliders work for a while then stop working 

Gestures on sliders are a little tricky because we are in scrolling views (both horizontal and vertical)
You have to hold your finger a little bit before dragging the slider

**Comment by kennymc-c** [comment]
> You have to hold your finger a little bit before dragging the slider

Ahh, that was the trick!

Just one thing that's not working: With lights that only support brightness and color temperature the ct slider can be adjusted but it doesn't have an effect. On the remote this slider works and it also works with app using color lights

**Comment by albaintor** [comment]
Can you confirm this still does not work with the new release ? This is strange, maybe the reported features by the entity light are not correct

**Comment by kennymc-c** [comment]
Yes, still preset with 115. The ct slider is also at 0% for all non color lights. The correct value is shown on the remote. Also with both color and non color lights the ct slider turns off the light when it's 0% which is not happening with the remote ui.

**Comment by kennymc-c** [comment]
No, the color temperature slider still doesn't work

**Comment by albaintor** [comment]
You're right, it worked some time ago. I am on it

**Comment by albaintor** [comment]
Fixed in build > 133

**Comment by kennymc-c** [comment]
Still the exact same behaviour as before with 1.2.0 (133)

**Comment by albaintor** [comment]
Can you double check please ? I can change temperature settings and it works on my version (I am on 1.2.1 now)
![image](https://github.com/user-attachments/assets/f427ff2f-8ead-4336-94a9-252af1f53eae)

**Comment by kennymc-c** [comment]
Your screenshot shows a color light. The issue only happens with lights that support color temperature but no color.

I also noticed that after changign the ct slider with color lights, where the slider works, the percentage value changes to a completly different value. But the slider stays at the same position:

https://github.com/user-attachments/assets/ca85f115-a2a2-47b1-921e-906e5d27bb39

All problems are not happening when using the remote itself. Also the color temperature slider works different as the color is less saturated when using the remote.

**Comment by albaintor** [comment]
This other issue is related to the remote that is not able to process changes fast enough, although I added a debounce mechanism : when you move the slider, I don't send the changed value each time but after 500ms. But even though the remote is slow to process changes. On my side it goes through HA then Philips Hue. I guess this is faster going through Philips Hue integration directly. 

At the end of the video we can see that the last changed CT is not taken into account but there is nothing I can do about it when the remote fails.

**Comment by kennymc-c** [comment]
I think i just cut the video to early so the last command is also recognized.
What do you mean by the remote is not fast enough? On the remote itself I don't have these problems. I'm using the Hue integration directly.

**Comment by albaintor** [comment]
The remote is not very reactive to handle commands, especially with HA in the chain. I understand this is better with Hue integration. So when you move the slider, the commands are not processed quickly. On the remote this is faster of course because the front end is directly connected to the backend and the remote doesn't have to handle API request & answers.
And sometimes some commands fails for some reason (weak wifi connection, a chain of commands not processed fast enough...)

This is the reason why I introduced a debounce mechanism to avoid flooding but sometimes the remote is just too "busy"

**Comment by albaintor** [comment]
I have fixed it, it will be included in 1.7.6

**Comment by kennymc-c** [comment]
Thanks, now it works.
The only things thats missing is the correct value of the color temperature and color wheel after turning on the light. By default the ct slider is at 0% and the color wheel at a random position. These values only seem to be updated if the parameter is updated. The ct slider value also sometimes shows a value >0 % but actual slider is at 0%. I also noticed some dropouts where I had to change a paramter again because it was not updated. Could be due to a interrupted websockets connection.

**Comment by albaintor** [comment]
This is strange : the color temperature is not systematically submitted by the remote. I have 2 different groups of lights.
I guess that if one bulb in a given group doesn't support color temperature, it won't be transmitted.
This is probably HA's fault.

Anyway, I have added a conversion method from RGB to temperature (Kelvin) : when the temperature is missing, I calculate it from the RGB values.

**Comment by kennymc-c** [comment]
Showing the correct ct value still doesn't work. For non color lights the app now always shows 100% after turning on.
Color lights now sometimes show an old or wrong value even after pull to refresh or changing the value.

**Comment by albaintor** [comment]
I can't reproduce this : I have some non-colored hue lights (handled through HA integration) and the CT slider reflects the same temperature as on the remote, so not necessarily 100%.
I have also some lights that don't support CT and in that case the CT slider is hidden
